version: 2
updates:
- package-ecosystem: nuget
  directory: "/msgraph-mail/dotnet"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/msgraph-mail/java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/msgraph-mail/typescript"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/template/dotnet"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/template/java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/template/typescript"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
