name: Build and test Java Get Started sample

on:
  push:
    branches:
      - main
      - regen/clients-**
    paths:
      - 'get-started/azure-auth/java/**'
      - 'get-started/quickstart/java/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'get-started/azure-auth/java/**'
      - 'get-started/quickstart/java/**'

jobs:
  build-azure:

    defaults:
      run:
        working-directory: get-started/azure-auth/java/

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        build-root-directory: get-started/azure-auth/java/
        arguments: build

  build-quickstart:

    defaults:
      run:
        working-directory: get-started/quickstart/java/

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        build-root-directory: get-started/quickstart/java/
        arguments: build
