name: Build and test .NET Get Started sample

on:
  push:
    branches:
      - main
      - regen/clients-**
    paths:
      - 'get-started/azure-auth/dotnet/**'
      - 'get-started/azure-auth/cli/**'
      - 'get-started/quickstart/dotnet/**'
      - 'get-started/quickstart/cli/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'get-started/azure-auth/dotnet/**'
      - 'get-started/azure-auth/cli/**'
      - 'get-started/quickstart/dotnet/**'
      - 'get-started/quickstart/cli/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: get-started/azure-auth/dotnet/src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: get-started/azure-auth/dotnet/src/

    - name: Restore dependencies
      run: dotnet restore
      working-directory: get-started/azure-auth/cli/src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: get-started/azure-auth/cli/src/

    - name: Restore dependencies
      run: dotnet restore
      working-directory: get-started/quickstart/dotnet/src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: get-started/quickstart/dotnet/src/

    - name: Restore dependencies
      run: dotnet restore
      working-directory: get-started/quickstart/cli/src/
    - name: Build
      run: dotnet build --no-restore
      working-directory: get-started/quickstart/cli/src/
