name: Build and test .NET Get Started sample

on:
  push:
    branches: [ main ]
    paths:
      - 'get-started/azure-auth/dotnet/**'
      - 'get-started/azure-auth/cli/**'
      - 'get-started/quickstart/dotnet/**'
      - 'get-started/quickstart/cli/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'get-started/azure-auth/dotnet/**'
      - 'get-started/azure-auth/cli/**'
      - 'get-started/quickstart/dotnet/**'
      - 'get-started/quickstart/cli/**'

jobs:
  build:

    defaults:
      run:
        working-directory: get-started/azure-auth/dotnet/src/

    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
        - get-started/azure-auth/dotnet/src/
        - get-started/azure-auth/cli/src/
        - get-started/quickstart/dotnet/src/
        - get-started/quickstart/cli/src/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
