name: Build and test ToDoItem sample .NET client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'sample-api/clients/dotnet**'

jobs:
  build:

    defaults:
      run:
        working-directory: sample-api/clients/dotnet

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
